// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	"database/sql"
	"github.com/ghulammuzz/backend-parkerin/internal/applicants/handler"
	"github.com/ghulammuzz/backend-parkerin/internal/applicants/repo"
	"github.com/ghulammuzz/backend-parkerin/internal/applicants/svc"
	repo2 "github.com/ghulammuzz/backend-parkerin/internal/store/repo"
	"github.com/ghulammuzz/backend-parkerin/internal/store/svc"
	repo3 "github.com/ghulammuzz/backend-parkerin/internal/users/repo"
)

// Injectors from wire.go:

func InitializedApplicationService(sb *sql.DB) *handler.ApplicationHandler {
	applicationRepository := repo.NewApplicationRepository(sb)
	storeRepository := repo2.NewStoreRepository(sb)
	userRepository := repo3.NewUserRepository(sb)
	applicationService := service.NewApplicationService(applicationRepository, storeRepository, userRepository)
	storeService := svc.NewStoreService(storeRepository, userRepository, applicationRepository)
	applicationHandler := handler.NewApplicationHandler(applicationService, storeService)
	return applicationHandler
}
