// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	"database/sql"

	"github.com/ghulammuzz/backend-parkerin/internal/payment/handler"
	"github.com/ghulammuzz/backend-parkerin/internal/payment/svc"
	repo2 "github.com/ghulammuzz/backend-parkerin/internal/users/repo"
	"github.com/midtrans/midtrans-go/snap"
)

// Injectors from wire.go:

func InitializedPaymentService(sb *sql.DB, midtransClient *snap.Client) *handler.PaymentHandler {
	userRepository := repo2.NewUserRepository(sb)
	paymentService := svc.NewPaymentService(userRepository, midtransClient)
	paymentHandler := handler.NewPaymentHandler(paymentService)
	return paymentHandler
}
