// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	"database/sql"
	repo3 "github.com/ghulammuzz/backend-parkerin/internal/applicants/repo"
	"github.com/ghulammuzz/backend-parkerin/internal/store/handler"
	"github.com/ghulammuzz/backend-parkerin/internal/store/repo"
	"github.com/ghulammuzz/backend-parkerin/internal/store/svc"
	repo2 "github.com/ghulammuzz/backend-parkerin/internal/users/repo"
)

// Injectors from wire.go:

func InitializedStoreService(sb *sql.DB) *handler.StoreHandler {
	storeRepository := repo.NewStoreRepository(sb)
	userRepository := repo2.NewUserRepository(sb)
	applicationRepository := repo3.NewApplicationRepository(sb)
	storeService := svc.NewStoreService(storeRepository, userRepository, applicationRepository)
	storeHandler := handler.NewStoreHandler(storeService)
	return storeHandler
}
